#!/usr/bin/env python3
import sys
import os
from os.path import abspath, dirname, join

proj_dir = abspath(join(dirname(__file__), '..'))
sys.path.insert(0, proj_dir)

from scuba.__main__ import main
main()
